name: login
description: A new Flutter project.
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  untitled2: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mohamed.jpg
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf